services:
  eshopdb:
   image: postgres

  distributedcahce:
   image: redis
  seq:
   image: datalust/seq:latest

  messagebus:
   image: rabbitmq:management
  identity:
   image: quay.io/keycloak/keycloak:24.0.3

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstraper/Api/Dockerfile

volumes:
  postgres_eshopdb:

